const { Types } = require("mongoose");

// A MongoDB aggregation pipeline is a sequence of stages.
// Every stage receives in input a set of documents,
// applies some transformation, then pass the transformed document to the next stage
const pipeline = (id) => [
    // outputs all documents with the given id
    {
        $match: { _id: new Types.ObjectId(`${id}`) }
    },
    // Generate an join between the users collection and the collection that uses this pipeline (Auctions in this case)
    {
        $lookup: {
            from: "users",
            localField: "owner",
            foreignField: "_id",
            as: "owner"
        }
    },
    // Destructure the array generated by the previous stage
    {
        $unwind: "$owner"
    },
    // Select with field to remove in the output document
    {
        $unset: ["owner.name", "owner.surname", "owner.password", "owner.__v"]
    }
];

module.exports = pipeline;